/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ShippingAddressService } from "../shippingAddress.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ShippingAddressCreateInput } from "./ShippingAddressCreateInput";
import { ShippingAddress } from "./ShippingAddress";
import { ShippingAddressFindManyArgs } from "./ShippingAddressFindManyArgs";
import { ShippingAddressWhereUniqueInput } from "./ShippingAddressWhereUniqueInput";
import { ShippingAddressUpdateInput } from "./ShippingAddressUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ShippingAddressControllerBase {
  constructor(
    protected readonly service: ShippingAddressService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ShippingAddress })
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createShippingAddress(
    @common.Body() data: ShippingAddressCreateInput
  ): Promise<ShippingAddress> {
    return await this.service.createShippingAddress({
      data: data,
      select: {
        addressName: true,
        city: true,
        country: true,
        createdAt: true,
        houseNo: true,
        id: true,
        nerarestBusstop: true,
        postalCode: true,
        state: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ShippingAddress] })
  @ApiNestedQuery(ShippingAddressFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shippingAddresses(
    @common.Req() request: Request
  ): Promise<ShippingAddress[]> {
    const args = plainToClass(ShippingAddressFindManyArgs, request.query);
    return this.service.shippingAddresses({
      ...args,
      select: {
        addressName: true,
        city: true,
        country: true,
        createdAt: true,
        houseNo: true,
        id: true,
        nerarestBusstop: true,
        postalCode: true,
        state: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ShippingAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shippingAddress(
    @common.Param() params: ShippingAddressWhereUniqueInput
  ): Promise<ShippingAddress | null> {
    const result = await this.service.shippingAddress({
      where: params,
      select: {
        addressName: true,
        city: true,
        country: true,
        createdAt: true,
        houseNo: true,
        id: true,
        nerarestBusstop: true,
        postalCode: true,
        state: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ShippingAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateShippingAddress(
    @common.Param() params: ShippingAddressWhereUniqueInput,
    @common.Body() data: ShippingAddressUpdateInput
  ): Promise<ShippingAddress | null> {
    try {
      return await this.service.updateShippingAddress({
        where: params,
        data: data,
        select: {
          addressName: true,
          city: true,
          country: true,
          createdAt: true,
          houseNo: true,
          id: true,
          nerarestBusstop: true,
          postalCode: true,
          state: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ShippingAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteShippingAddress(
    @common.Param() params: ShippingAddressWhereUniqueInput
  ): Promise<ShippingAddress | null> {
    try {
      return await this.service.deleteShippingAddress({
        where: params,
        select: {
          addressName: true,
          city: true,
          country: true,
          createdAt: true,
          houseNo: true,
          id: true,
          nerarestBusstop: true,
          postalCode: true,
          state: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: ShippingAddressWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "update",
    possession: "any",
  })
  async connectUsers(
    @common.Param() params: ShippingAddressWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateShippingAddress({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "update",
    possession: "any",
  })
  async updateUsers(
    @common.Param() params: ShippingAddressWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateShippingAddress({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "ShippingAddress",
    action: "update",
    possession: "any",
  })
  async disconnectUsers(
    @common.Param() params: ShippingAddressWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateShippingAddress({
      where: params,
      data,
      select: { id: true },
    });
  }
}
