/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ModelService } from "../model.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ModelCreateInput } from "./ModelCreateInput";
import { Model } from "./Model";
import { ModelFindManyArgs } from "./ModelFindManyArgs";
import { ModelWhereUniqueInput } from "./ModelWhereUniqueInput";
import { ModelUpdateInput } from "./ModelUpdateInput";
import { ApparelFindManyArgs } from "../../apparel/base/ApparelFindManyArgs";
import { Apparel } from "../../apparel/base/Apparel";
import { ApparelWhereUniqueInput } from "../../apparel/base/ApparelWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ModelControllerBase {
  constructor(
    protected readonly service: ModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Model })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createModel(@common.Body() data: ModelCreateInput): Promise<Model> {
    return await this.service.createModel({
      data: {
        ...data,

        modelProperties: data.modelProperties
          ? {
              connect: data.modelProperties,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        modelFile: true,

        modelProperties: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Model] })
  @ApiNestedQuery(ModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async models(@common.Req() request: Request): Promise<Model[]> {
    const args = plainToClass(ModelFindManyArgs, request.query);
    return this.service.models({
      ...args,
      select: {
        createdAt: true,
        id: true,
        modelFile: true,

        modelProperties: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async model(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    const result = await this.service.model({
      where: params,
      select: {
        createdAt: true,
        id: true,
        modelFile: true,

        modelProperties: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateModel(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() data: ModelUpdateInput
  ): Promise<Model | null> {
    try {
      return await this.service.updateModel({
        where: params,
        data: {
          ...data,

          modelProperties: data.modelProperties
            ? {
                connect: data.modelProperties,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          modelFile: true,

          modelProperties: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteModel(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    try {
      return await this.service.deleteModel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          modelFile: true,

          modelProperties: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/apparels")
  @ApiNestedQuery(ApparelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "any",
  })
  async findApparels(
    @common.Req() request: Request,
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Apparel[]> {
    const query = plainToClass(ApparelFindManyArgs, request.query);
    const results = await this.service.findApparels(params.id, {
      ...query,
      select: {
        apparelDesc: true,
        apparelName: true,
        apparelPrice: true,

        apparelType: {
          select: {
            id: true,
          },
        },

        brand: {
          select: {
            id: true,
          },
        },

        cartItem: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        discountedPrice: true,
        discountEndDate: true,
        discountPercentage: true,
        discountStartDate: true,
        id: true,
        isDiscounted: true,

        mainCategory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        wishlistItems: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async connectApparels(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        connect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async updateApparels(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        set: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async disconnectApparels(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        disconnect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
