/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Apparel } from "./Apparel";
import { ApparelCountArgs } from "./ApparelCountArgs";
import { ApparelFindManyArgs } from "./ApparelFindManyArgs";
import { ApparelFindUniqueArgs } from "./ApparelFindUniqueArgs";
import { CreateApparelArgs } from "./CreateApparelArgs";
import { UpdateApparelArgs } from "./UpdateApparelArgs";
import { DeleteApparelArgs } from "./DeleteApparelArgs";
import { MaterialFindManyArgs } from "../../material/base/MaterialFindManyArgs";
import { Material } from "../../material/base/Material";
import { ModelFindManyArgs } from "../../model/base/ModelFindManyArgs";
import { Model } from "../../model/base/Model";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { SizeFindManyArgs } from "../../size/base/SizeFindManyArgs";
import { Size } from "../../size/base/Size";
import { SubCategoryFindManyArgs } from "../../subCategory/base/SubCategoryFindManyArgs";
import { SubCategory } from "../../subCategory/base/SubCategory";
import { SubSubcategoryFindManyArgs } from "../../subSubcategory/base/SubSubcategoryFindManyArgs";
import { SubSubcategory } from "../../subSubcategory/base/SubSubcategory";
import { ApparelType } from "../../apparelType/base/ApparelType";
import { Brand } from "../../brand/base/Brand";
import { CartItem } from "../../cartItem/base/CartItem";
import { MainCategory } from "../../mainCategory/base/MainCategory";
import { WishlistItems } from "../../wishlistItems/base/WishlistItems";
import { ApparelService } from "../apparel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Apparel)
export class ApparelResolverBase {
  constructor(
    protected readonly service: ApparelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "any",
  })
  async _apparelsMeta(
    @graphql.Args() args: ApparelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Apparel])
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "any",
  })
  async apparels(
    @graphql.Args() args: ApparelFindManyArgs
  ): Promise<Apparel[]> {
    return this.service.apparels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Apparel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "own",
  })
  async apparel(
    @graphql.Args() args: ApparelFindUniqueArgs
  ): Promise<Apparel | null> {
    const result = await this.service.apparel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Apparel)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "create",
    possession: "any",
  })
  async createApparel(
    @graphql.Args() args: CreateApparelArgs
  ): Promise<Apparel> {
    return await this.service.createApparel({
      ...args,
      data: {
        ...args.data,

        apparelType: args.data.apparelType
          ? {
              connect: args.data.apparelType,
            }
          : undefined,

        brand: args.data.brand
          ? {
              connect: args.data.brand,
            }
          : undefined,

        cartItem: args.data.cartItem
          ? {
              connect: args.data.cartItem,
            }
          : undefined,

        mainCategory: args.data.mainCategory
          ? {
              connect: args.data.mainCategory,
            }
          : undefined,

        wishlistItems: args.data.wishlistItems
          ? {
              connect: args.data.wishlistItems,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Apparel)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "update",
    possession: "any",
  })
  async updateApparel(
    @graphql.Args() args: UpdateApparelArgs
  ): Promise<Apparel | null> {
    try {
      return await this.service.updateApparel({
        ...args,
        data: {
          ...args.data,

          apparelType: args.data.apparelType
            ? {
                connect: args.data.apparelType,
              }
            : undefined,

          brand: args.data.brand
            ? {
                connect: args.data.brand,
              }
            : undefined,

          cartItem: args.data.cartItem
            ? {
                connect: args.data.cartItem,
              }
            : undefined,

          mainCategory: args.data.mainCategory
            ? {
                connect: args.data.mainCategory,
              }
            : undefined,

          wishlistItems: args.data.wishlistItems
            ? {
                connect: args.data.wishlistItems,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Apparel)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "delete",
    possession: "any",
  })
  async deleteApparel(
    @graphql.Args() args: DeleteApparelArgs
  ): Promise<Apparel | null> {
    try {
      return await this.service.deleteApparel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Material], { name: "materials" })
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "any",
  })
  async findMaterials(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: MaterialFindManyArgs
  ): Promise<Material[]> {
    const results = await this.service.findMaterials(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Model], { name: "models" })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "read",
    possession: "any",
  })
  async findModels(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: ModelFindManyArgs
  ): Promise<Model[]> {
    const results = await this.service.findModels(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Review], { name: "reviews" })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Size], { name: "sizes" })
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "read",
    possession: "any",
  })
  async findSizes(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: SizeFindManyArgs
  ): Promise<Size[]> {
    const results = await this.service.findSizes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SubCategory], { name: "subCategories" })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "any",
  })
  async findSubCategories(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: SubCategoryFindManyArgs
  ): Promise<SubCategory[]> {
    const results = await this.service.findSubCategories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SubSubcategory], { name: "subSubcategories" })
  @nestAccessControl.UseRoles({
    resource: "SubSubcategory",
    action: "read",
    possession: "any",
  })
  async findSubSubcategories(
    @graphql.Parent() parent: Apparel,
    @graphql.Args() args: SubSubcategoryFindManyArgs
  ): Promise<SubSubcategory[]> {
    const results = await this.service.findSubSubcategories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => ApparelType, {
    nullable: true,
    name: "apparelType",
  })
  @nestAccessControl.UseRoles({
    resource: "ApparelType",
    action: "read",
    possession: "any",
  })
  async getApparelType(
    @graphql.Parent() parent: Apparel
  ): Promise<ApparelType | null> {
    const result = await this.service.getApparelType(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Brand, {
    nullable: true,
    name: "brand",
  })
  @nestAccessControl.UseRoles({
    resource: "Brand",
    action: "read",
    possession: "any",
  })
  async getBrand(@graphql.Parent() parent: Apparel): Promise<Brand | null> {
    const result = await this.service.getBrand(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => CartItem, {
    nullable: true,
    name: "cartItem",
  })
  @nestAccessControl.UseRoles({
    resource: "CartItem",
    action: "read",
    possession: "any",
  })
  async getCartItem(
    @graphql.Parent() parent: Apparel
  ): Promise<CartItem | null> {
    const result = await this.service.getCartItem(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => MainCategory, {
    nullable: true,
    name: "mainCategory",
  })
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "read",
    possession: "any",
  })
  async getMainCategory(
    @graphql.Parent() parent: Apparel
  ): Promise<MainCategory | null> {
    const result = await this.service.getMainCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => WishlistItems, {
    nullable: true,
    name: "wishlistItems",
  })
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "read",
    possession: "any",
  })
  async getWishlistItems(
    @graphql.Parent() parent: Apparel
  ): Promise<WishlistItems | null> {
    const result = await this.service.getWishlistItems(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
