/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Apparel, // @ts-ignore
  Order,
} from "@prisma/client";

export class ApparelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ApparelCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelCountArgs>
  ): Promise<number> {
    return this.prisma.apparel.count(args);
  }

  async apparels<T extends Prisma.ApparelFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelFindManyArgs>
  ): Promise<Apparel[]> {
    return this.prisma.apparel.findMany(args);
  }
  async apparel<T extends Prisma.ApparelFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelFindUniqueArgs>
  ): Promise<Apparel | null> {
    return this.prisma.apparel.findUnique(args);
  }
  async createApparel<T extends Prisma.ApparelCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelCreateArgs>
  ): Promise<Apparel> {
    return this.prisma.apparel.create<T>(args);
  }
  async updateApparel<T extends Prisma.ApparelUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelUpdateArgs>
  ): Promise<Apparel> {
    return this.prisma.apparel.update<T>(args);
  }
  async deleteApparel<T extends Prisma.ApparelDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApparelDeleteArgs>
  ): Promise<Apparel> {
    return this.prisma.apparel.delete(args);
  }

  async findOrders(
    parentId: string,
    args: Prisma.OrderFindManyArgs
  ): Promise<Order[]> {
    return this.prisma.apparel
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .orders(args);
  }
}
