/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Measurement } from "./Measurement";
import { MeasurementCountArgs } from "./MeasurementCountArgs";
import { MeasurementFindManyArgs } from "./MeasurementFindManyArgs";
import { MeasurementFindUniqueArgs } from "./MeasurementFindUniqueArgs";
import { CreateMeasurementArgs } from "./CreateMeasurementArgs";
import { UpdateMeasurementArgs } from "./UpdateMeasurementArgs";
import { DeleteMeasurementArgs } from "./DeleteMeasurementArgs";
import { SizingUnit } from "../../sizingUnit/base/SizingUnit";
import { MeasurementService } from "../measurement.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Measurement)
export class MeasurementResolverBase {
  constructor(
    protected readonly service: MeasurementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "read",
    possession: "any",
  })
  async _measurementsMeta(
    @graphql.Args() args: MeasurementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Measurement])
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "read",
    possession: "any",
  })
  async measurements(
    @graphql.Args() args: MeasurementFindManyArgs
  ): Promise<Measurement[]> {
    return this.service.measurements(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Measurement, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "read",
    possession: "own",
  })
  async measurement(
    @graphql.Args() args: MeasurementFindUniqueArgs
  ): Promise<Measurement | null> {
    const result = await this.service.measurement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Measurement)
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "create",
    possession: "any",
  })
  async createMeasurement(
    @graphql.Args() args: CreateMeasurementArgs
  ): Promise<Measurement> {
    return await this.service.createMeasurement({
      ...args,
      data: {
        ...args.data,

        sizingUnit: args.data.sizingUnit
          ? {
              connect: args.data.sizingUnit,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Measurement)
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "update",
    possession: "any",
  })
  async updateMeasurement(
    @graphql.Args() args: UpdateMeasurementArgs
  ): Promise<Measurement | null> {
    try {
      return await this.service.updateMeasurement({
        ...args,
        data: {
          ...args.data,

          sizingUnit: args.data.sizingUnit
            ? {
                connect: args.data.sizingUnit,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Measurement)
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "delete",
    possession: "any",
  })
  async deleteMeasurement(
    @graphql.Args() args: DeleteMeasurementArgs
  ): Promise<Measurement | null> {
    try {
      return await this.service.deleteMeasurement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SizingUnit, {
    nullable: true,
    name: "sizingUnit",
  })
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "read",
    possession: "any",
  })
  async getSizingUnit(
    @graphql.Parent() parent: Measurement
  ): Promise<SizingUnit | null> {
    const result = await this.service.getSizingUnit(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
