/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CartItem, // @ts-ignore
  Apparel, // @ts-ignore
  Cart,
} from "@prisma/client";

export class CartItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CartItemCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemCountArgs>
  ): Promise<number> {
    return this.prisma.cartItem.count(args);
  }

  async cartItems<T extends Prisma.CartItemFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemFindManyArgs>
  ): Promise<CartItem[]> {
    return this.prisma.cartItem.findMany(args);
  }
  async cartItem<T extends Prisma.CartItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemFindUniqueArgs>
  ): Promise<CartItem | null> {
    return this.prisma.cartItem.findUnique(args);
  }
  async createCartItem<T extends Prisma.CartItemCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemCreateArgs>
  ): Promise<CartItem> {
    return this.prisma.cartItem.create<T>(args);
  }
  async updateCartItem<T extends Prisma.CartItemUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemUpdateArgs>
  ): Promise<CartItem> {
    return this.prisma.cartItem.update<T>(args);
  }
  async deleteCartItem<T extends Prisma.CartItemDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CartItemDeleteArgs>
  ): Promise<CartItem> {
    return this.prisma.cartItem.delete(args);
  }

  async findApparels(
    parentId: string,
    args: Prisma.ApparelFindManyArgs
  ): Promise<Apparel[]> {
    return this.prisma.cartItem
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .apparels(args);
  }

  async getCart(parentId: string): Promise<Cart | null> {
    return this.prisma.cartItem
      .findUnique({
        where: { id: parentId },
      })
      .cart();
  }
}
