/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SizeService } from "../size.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SizeCreateInput } from "./SizeCreateInput";
import { Size } from "./Size";
import { SizeFindManyArgs } from "./SizeFindManyArgs";
import { SizeWhereUniqueInput } from "./SizeWhereUniqueInput";
import { SizeUpdateInput } from "./SizeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SizeControllerBase {
  constructor(
    protected readonly service: SizeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Size })
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSize(@common.Body() data: SizeCreateInput): Promise<Size> {
    return await this.service.createSize({
      data: {
        ...data,

        apparel: data.apparel
          ? {
              connect: data.apparel,
            }
          : undefined,

        apparelType: data.apparelType
          ? {
              connect: data.apparelType,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        apparel: {
          select: {
            id: true,
          },
        },

        apparelType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        measurements: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Size] })
  @ApiNestedQuery(SizeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sizes(@common.Req() request: Request): Promise<Size[]> {
    const args = plainToClass(SizeFindManyArgs, request.query);
    return this.service.sizes({
      ...args,
      select: {
        apparel: {
          select: {
            id: true,
          },
        },

        apparelType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        measurements: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async size(
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<Size | null> {
    const result = await this.service.size({
      where: params,
      select: {
        apparel: {
          select: {
            id: true,
          },
        },

        apparelType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        measurements: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSize(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() data: SizeUpdateInput
  ): Promise<Size | null> {
    try {
      return await this.service.updateSize({
        where: params,
        data: {
          ...data,

          apparel: data.apparel
            ? {
                connect: data.apparel,
              }
            : undefined,

          apparelType: data.apparelType
            ? {
                connect: data.apparelType,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          apparel: {
            select: {
              id: true,
            },
          },

          apparelType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          measurements: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Size",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSize(
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<Size | null> {
    try {
      return await this.service.deleteSize({
        where: params,
        select: {
          apparel: {
            select: {
              id: true,
            },
          },

          apparelType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          measurements: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
