/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WishlistItemsService } from "../wishlistItems.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WishlistItemsCreateInput } from "./WishlistItemsCreateInput";
import { WishlistItems } from "./WishlistItems";
import { WishlistItemsFindManyArgs } from "./WishlistItemsFindManyArgs";
import { WishlistItemsWhereUniqueInput } from "./WishlistItemsWhereUniqueInput";
import { WishlistItemsUpdateInput } from "./WishlistItemsUpdateInput";
import { ApparelFindManyArgs } from "../../apparel/base/ApparelFindManyArgs";
import { Apparel } from "../../apparel/base/Apparel";
import { ApparelWhereUniqueInput } from "../../apparel/base/ApparelWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WishlistItemsControllerBase {
  constructor(
    protected readonly service: WishlistItemsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WishlistItems })
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWishlistItems(
    @common.Body() data: WishlistItemsCreateInput
  ): Promise<WishlistItems> {
    return await this.service.createWishlistItems({
      data: {
        ...data,

        wishlist: data.wishlist
          ? {
              connect: data.wishlist,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WishlistItems] })
  @ApiNestedQuery(WishlistItemsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wishlistItemsItems(
    @common.Req() request: Request
  ): Promise<WishlistItems[]> {
    const args = plainToClass(WishlistItemsFindManyArgs, request.query);
    return this.service.wishlistItemsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WishlistItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wishlistItems(
    @common.Param() params: WishlistItemsWhereUniqueInput
  ): Promise<WishlistItems | null> {
    const result = await this.service.wishlistItems({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WishlistItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWishlistItems(
    @common.Param() params: WishlistItemsWhereUniqueInput,
    @common.Body() data: WishlistItemsUpdateInput
  ): Promise<WishlistItems | null> {
    try {
      return await this.service.updateWishlistItems({
        where: params,
        data: {
          ...data,

          wishlist: data.wishlist
            ? {
                connect: data.wishlist,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          wishlist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WishlistItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWishlistItems(
    @common.Param() params: WishlistItemsWhereUniqueInput
  ): Promise<WishlistItems | null> {
    try {
      return await this.service.deleteWishlistItems({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          wishlist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/apparels")
  @ApiNestedQuery(ApparelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "any",
  })
  async findApparels(
    @common.Req() request: Request,
    @common.Param() params: WishlistItemsWhereUniqueInput
  ): Promise<Apparel[]> {
    const query = plainToClass(ApparelFindManyArgs, request.query);
    const results = await this.service.findApparels(params.id, {
      ...query,
      select: {
        apparelDesc: true,
        apparelName: true,
        apparelPrice: true,

        apparelType: {
          select: {
            id: true,
          },
        },

        brand: {
          select: {
            id: true,
          },
        },

        cartItem: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        discountedPrice: true,
        discountEndDate: true,
        discountPercentage: true,
        discountStartDate: true,
        id: true,
        isDiscounted: true,

        mainCategory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        wishlistItems: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "update",
    possession: "any",
  })
  async connectApparels(
    @common.Param() params: WishlistItemsWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        connect: body,
      },
    };
    await this.service.updateWishlistItems({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "update",
    possession: "any",
  })
  async updateApparels(
    @common.Param() params: WishlistItemsWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        set: body,
      },
    };
    await this.service.updateWishlistItems({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/apparels")
  @nestAccessControl.UseRoles({
    resource: "WishlistItems",
    action: "update",
    possession: "any",
  })
  async disconnectApparels(
    @common.Param() params: WishlistItemsWhereUniqueInput,
    @common.Body() body: ApparelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apparels: {
        disconnect: body,
      },
    };
    await this.service.updateWishlistItems({
      where: params,
      data,
      select: { id: true },
    });
  }
}
