/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SizingUnitService } from "../sizingUnit.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SizingUnitCreateInput } from "./SizingUnitCreateInput";
import { SizingUnit } from "./SizingUnit";
import { SizingUnitFindManyArgs } from "./SizingUnitFindManyArgs";
import { SizingUnitWhereUniqueInput } from "./SizingUnitWhereUniqueInput";
import { SizingUnitUpdateInput } from "./SizingUnitUpdateInput";
import { MeasurementFindManyArgs } from "../../measurement/base/MeasurementFindManyArgs";
import { Measurement } from "../../measurement/base/Measurement";
import { MeasurementWhereUniqueInput } from "../../measurement/base/MeasurementWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SizingUnitControllerBase {
  constructor(
    protected readonly service: SizingUnitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SizingUnit })
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSizingUnit(
    @common.Body() data: SizingUnitCreateInput
  ): Promise<SizingUnit> {
    return await this.service.createSizingUnit({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SizingUnit] })
  @ApiNestedQuery(SizingUnitFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sizingUnits(@common.Req() request: Request): Promise<SizingUnit[]> {
    const args = plainToClass(SizingUnitFindManyArgs, request.query);
    return this.service.sizingUnits({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SizingUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sizingUnit(
    @common.Param() params: SizingUnitWhereUniqueInput
  ): Promise<SizingUnit | null> {
    const result = await this.service.sizingUnit({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SizingUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSizingUnit(
    @common.Param() params: SizingUnitWhereUniqueInput,
    @common.Body() data: SizingUnitUpdateInput
  ): Promise<SizingUnit | null> {
    try {
      return await this.service.updateSizingUnit({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SizingUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSizingUnit(
    @common.Param() params: SizingUnitWhereUniqueInput
  ): Promise<SizingUnit | null> {
    try {
      return await this.service.deleteSizingUnit({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/measurements")
  @ApiNestedQuery(MeasurementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Measurement",
    action: "read",
    possession: "any",
  })
  async findMeasurements(
    @common.Req() request: Request,
    @common.Param() params: SizingUnitWhereUniqueInput
  ): Promise<Measurement[]> {
    const query = plainToClass(MeasurementFindManyArgs, request.query);
    const results = await this.service.findMeasurements(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        sizingUnit: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/measurements")
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "update",
    possession: "any",
  })
  async connectMeasurements(
    @common.Param() params: SizingUnitWhereUniqueInput,
    @common.Body() body: MeasurementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      measurements: {
        connect: body,
      },
    };
    await this.service.updateSizingUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/measurements")
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "update",
    possession: "any",
  })
  async updateMeasurements(
    @common.Param() params: SizingUnitWhereUniqueInput,
    @common.Body() body: MeasurementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      measurements: {
        set: body,
      },
    };
    await this.service.updateSizingUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/measurements")
  @nestAccessControl.UseRoles({
    resource: "SizingUnit",
    action: "update",
    possession: "any",
  })
  async disconnectMeasurements(
    @common.Param() params: SizingUnitWhereUniqueInput,
    @common.Body() body: MeasurementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      measurements: {
        disconnect: body,
      },
    };
    await this.service.updateSizingUnit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
