import { ApparelType } from "../apparelType/ApparelType";
import { Brand } from "../brand/Brand";
import { CartItem } from "../cartItem/CartItem";
import { Decimal } from "decimal.js";
import { MainCategory } from "../mainCategory/MainCategory";
import { Material } from "../material/Material";
import { Model } from "../model/Model";
import { Review } from "../review/Review";
import { Size } from "../size/Size";
import { SubCategory } from "../subCategory/SubCategory";
import { SubSubcategory } from "../subSubcategory/SubSubcategory";
import { WishlistItems } from "../wishlistItems/WishlistItems";

export type Apparel = {
  apparelDesc: string | null;
  apparelName: string | null;
  apparelPrice: number | null;
  apparelType?: ApparelType | null;
  brand?: Brand | null;
  cartItem?: CartItem | null;
  createdAt: Date;
  discountedPrice: number | null;
  discountEndDate: Date | null;
  discountPercentage: Decimal | null;
  discountStartDate: Date | null;
  id: string;
  isDiscounted: boolean | null;
  mainCategory?: MainCategory | null;
  materials?: Array<Material>;
  models?: Array<Model>;
  reviews?: Array<Review>;
  sizes?: Array<Size>;
  subCategories?: Array<SubCategory>;
  subSubcategories?: Array<SubSubcategory>;
  updatedAt: Date;
  wishlistItems?: WishlistItems | null;
};
