import { ApparelTypeWhereUniqueInput } from "../apparelType/ApparelTypeWhereUniqueInput";
import { BrandWhereUniqueInput } from "../brand/BrandWhereUniqueInput";
import { CartItemWhereUniqueInput } from "../cartItem/CartItemWhereUniqueInput";
import { Decimal } from "decimal.js";
import { MainCategoryWhereUniqueInput } from "../mainCategory/MainCategoryWhereUniqueInput";
import { MaterialCreateNestedManyWithoutApparelsInput } from "./MaterialCreateNestedManyWithoutApparelsInput";
import { ModelCreateNestedManyWithoutApparelsInput } from "./ModelCreateNestedManyWithoutApparelsInput";
import { ReviewCreateNestedManyWithoutApparelsInput } from "./ReviewCreateNestedManyWithoutApparelsInput";
import { SizeCreateNestedManyWithoutApparelsInput } from "./SizeCreateNestedManyWithoutApparelsInput";
import { SubCategoryCreateNestedManyWithoutApparelsInput } from "./SubCategoryCreateNestedManyWithoutApparelsInput";
import { SubSubcategoryCreateNestedManyWithoutApparelsInput } from "./SubSubcategoryCreateNestedManyWithoutApparelsInput";
import { WishlistItemsWhereUniqueInput } from "../wishlistItems/WishlistItemsWhereUniqueInput";

export type ApparelCreateInput = {
  apparelDesc?: string | null;
  apparelName?: string | null;
  apparelPrice?: number | null;
  apparelType?: ApparelTypeWhereUniqueInput | null;
  brand?: BrandWhereUniqueInput | null;
  cartItem?: CartItemWhereUniqueInput | null;
  discountedPrice?: number | null;
  discountEndDate?: Date | null;
  discountPercentage?: Decimal | null;
  discountStartDate?: Date | null;
  isDiscounted?: boolean | null;
  mainCategory?: MainCategoryWhereUniqueInput | null;
  materials?: MaterialCreateNestedManyWithoutApparelsInput;
  models?: ModelCreateNestedManyWithoutApparelsInput;
  reviews?: ReviewCreateNestedManyWithoutApparelsInput;
  sizes?: SizeCreateNestedManyWithoutApparelsInput;
  subCategories?: SubCategoryCreateNestedManyWithoutApparelsInput;
  subSubcategories?: SubSubcategoryCreateNestedManyWithoutApparelsInput;
  wishlistItems?: WishlistItemsWhereUniqueInput | null;
};
