import { ApparelTypeWhereUniqueInput } from "../apparelType/ApparelTypeWhereUniqueInput";
import { BrandWhereUniqueInput } from "../brand/BrandWhereUniqueInput";
import { CartItemWhereUniqueInput } from "../cartItem/CartItemWhereUniqueInput";
import { Decimal } from "decimal.js";
import { MainCategoryWhereUniqueInput } from "../mainCategory/MainCategoryWhereUniqueInput";
import { MaterialUpdateManyWithoutApparelsInput } from "./MaterialUpdateManyWithoutApparelsInput";
import { ModelUpdateManyWithoutApparelsInput } from "./ModelUpdateManyWithoutApparelsInput";
import { ReviewUpdateManyWithoutApparelsInput } from "./ReviewUpdateManyWithoutApparelsInput";
import { SizeUpdateManyWithoutApparelsInput } from "./SizeUpdateManyWithoutApparelsInput";
import { SubCategoryUpdateManyWithoutApparelsInput } from "./SubCategoryUpdateManyWithoutApparelsInput";
import { SubSubcategoryUpdateManyWithoutApparelsInput } from "./SubSubcategoryUpdateManyWithoutApparelsInput";
import { WishlistItemsWhereUniqueInput } from "../wishlistItems/WishlistItemsWhereUniqueInput";

export type ApparelUpdateInput = {
  apparelDesc?: string | null;
  apparelName?: string | null;
  apparelPrice?: number | null;
  apparelType?: ApparelTypeWhereUniqueInput | null;
  brand?: BrandWhereUniqueInput | null;
  cartItem?: CartItemWhereUniqueInput | null;
  discountedPrice?: number | null;
  discountEndDate?: Date | null;
  discountPercentage?: Decimal | null;
  discountStartDate?: Date | null;
  isDiscounted?: boolean | null;
  mainCategory?: MainCategoryWhereUniqueInput | null;
  materials?: MaterialUpdateManyWithoutApparelsInput;
  models?: ModelUpdateManyWithoutApparelsInput;
  reviews?: ReviewUpdateManyWithoutApparelsInput;
  sizes?: SizeUpdateManyWithoutApparelsInput;
  subCategories?: SubCategoryUpdateManyWithoutApparelsInput;
  subSubcategories?: SubSubcategoryUpdateManyWithoutApparelsInput;
  wishlistItems?: WishlistItemsWhereUniqueInput | null;
};
