/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Material, // @ts-ignore
  Apparel,
} from "@prisma/client";

export class MaterialServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.MaterialCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCountArgs>
  ): Promise<number> {
    return this.prisma.material.count(args);
  }

  async materials<T extends Prisma.MaterialFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialFindManyArgs>
  ): Promise<Material[]> {
    return this.prisma.material.findMany(args);
  }
  async material<T extends Prisma.MaterialFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialFindUniqueArgs>
  ): Promise<Material | null> {
    return this.prisma.material.findUnique(args);
  }
  async createMaterial<T extends Prisma.MaterialCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCreateArgs>
  ): Promise<Material> {
    return this.prisma.material.create<T>(args);
  }
  async updateMaterial<T extends Prisma.MaterialUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialUpdateArgs>
  ): Promise<Material> {
    return this.prisma.material.update<T>(args);
  }
  async deleteMaterial<T extends Prisma.MaterialDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialDeleteArgs>
  ): Promise<Material> {
    return this.prisma.material.delete(args);
  }

  async getApparel(parentId: string): Promise<Apparel | null> {
    return this.prisma.material
      .findUnique({
        where: { id: parentId },
      })
      .apparel();
  }
}
