/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SubCategory, // @ts-ignore
  Apparel, // @ts-ignore
  MainCategory, // @ts-ignore
  SubSubcategory,
} from "@prisma/client";

export class SubCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.SubCategoryCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryCountArgs>
  ): Promise<number> {
    return this.prisma.subCategory.count(args);
  }

  async subCategories<T extends Prisma.SubCategoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryFindManyArgs>
  ): Promise<SubCategory[]> {
    return this.prisma.subCategory.findMany(args);
  }
  async subCategory<T extends Prisma.SubCategoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryFindUniqueArgs>
  ): Promise<SubCategory | null> {
    return this.prisma.subCategory.findUnique(args);
  }
  async createSubCategory<T extends Prisma.SubCategoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryCreateArgs>
  ): Promise<SubCategory> {
    return this.prisma.subCategory.create<T>(args);
  }
  async updateSubCategory<T extends Prisma.SubCategoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryUpdateArgs>
  ): Promise<SubCategory> {
    return this.prisma.subCategory.update<T>(args);
  }
  async deleteSubCategory<T extends Prisma.SubCategoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SubCategoryDeleteArgs>
  ): Promise<SubCategory> {
    return this.prisma.subCategory.delete(args);
  }

  async findApparel(
    parentId: string,
    args: Prisma.ApparelFindManyArgs
  ): Promise<Apparel[]> {
    return this.prisma.subCategory
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .apparel(args);
  }

  async findMainCategories(
    parentId: string,
    args: Prisma.MainCategoryFindManyArgs
  ): Promise<MainCategory[]> {
    return this.prisma.subCategory
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .mainCategories(args);
  }

  async findSubSubcategory(
    parentId: string,
    args: Prisma.SubSubcategoryFindManyArgs
  ): Promise<SubSubcategory[]> {
    return this.prisma.subCategory
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .subSubcategory(args);
  }
}
