/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { MainCategory } from "./MainCategory";
import { MainCategoryCountArgs } from "./MainCategoryCountArgs";
import { MainCategoryFindManyArgs } from "./MainCategoryFindManyArgs";
import { MainCategoryFindUniqueArgs } from "./MainCategoryFindUniqueArgs";
import { CreateMainCategoryArgs } from "./CreateMainCategoryArgs";
import { UpdateMainCategoryArgs } from "./UpdateMainCategoryArgs";
import { DeleteMainCategoryArgs } from "./DeleteMainCategoryArgs";
import { ApparelFindManyArgs } from "../../apparel/base/ApparelFindManyArgs";
import { Apparel } from "../../apparel/base/Apparel";
import { SubCategoryFindManyArgs } from "../../subCategory/base/SubCategoryFindManyArgs";
import { SubCategory } from "../../subCategory/base/SubCategory";
import { MainCategoryService } from "../mainCategory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MainCategory)
export class MainCategoryResolverBase {
  constructor(
    protected readonly service: MainCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "read",
    possession: "any",
  })
  async _mainCategoriesMeta(
    @graphql.Args() args: MainCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MainCategory])
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "read",
    possession: "any",
  })
  async mainCategories(
    @graphql.Args() args: MainCategoryFindManyArgs
  ): Promise<MainCategory[]> {
    return this.service.mainCategories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MainCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "read",
    possession: "own",
  })
  async mainCategory(
    @graphql.Args() args: MainCategoryFindUniqueArgs
  ): Promise<MainCategory | null> {
    const result = await this.service.mainCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MainCategory)
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "create",
    possession: "any",
  })
  async createMainCategory(
    @graphql.Args() args: CreateMainCategoryArgs
  ): Promise<MainCategory> {
    return await this.service.createMainCategory({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MainCategory)
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "update",
    possession: "any",
  })
  async updateMainCategory(
    @graphql.Args() args: UpdateMainCategoryArgs
  ): Promise<MainCategory | null> {
    try {
      return await this.service.updateMainCategory({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MainCategory)
  @nestAccessControl.UseRoles({
    resource: "MainCategory",
    action: "delete",
    possession: "any",
  })
  async deleteMainCategory(
    @graphql.Args() args: DeleteMainCategoryArgs
  ): Promise<MainCategory | null> {
    try {
      return await this.service.deleteMainCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Apparel], { name: "apparels" })
  @nestAccessControl.UseRoles({
    resource: "Apparel",
    action: "read",
    possession: "any",
  })
  async findApparels(
    @graphql.Parent() parent: MainCategory,
    @graphql.Args() args: ApparelFindManyArgs
  ): Promise<Apparel[]> {
    const results = await this.service.findApparels(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SubCategory], { name: "subCategory" })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "any",
  })
  async findSubCategory(
    @graphql.Parent() parent: MainCategory,
    @graphql.Args() args: SubCategoryFindManyArgs
  ): Promise<SubCategory[]> {
    const results = await this.service.findSubCategory(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
